# Generated by Django 4.2.2 on 2023-09-19 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_condition',
            name='indicator_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backtesting.indicator'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backtesting.entry_condition'),
        ),
    ]
