# Generated by Django 4.2.2 on 2023-09-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0002_entry_condition_indicator_1_strategy_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMA',
            fields=[
                ('indicator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backtesting.indicator')),
                ('window', models.IntegerField()),
            ],
            bases=('backtesting.indicator',),
        ),
    ]
