# Generated by Django 4.2.2 on 2023-09-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0003_sma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window', models.IntegerField()),
                ('weights', models.IntegerField()),
                ('fast_period', models.IntegerField()),
                ('slow_period', models.IntegerField()),
            ],
        ),
    ]
